# Generated by Django 3.0 on 2021-04-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('description', models.TextField(max_length=500)),
                ('rating', models.IntegerField(default=0)),
                ('no_of_rating', models.IntegerField(default=0)),
            ],
        ),
    ]
