# Generated by Django 3.0 on 2021-01-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='no_of_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
